### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by seyhadot** [Unhall0w3d/nocthoughts-dotfiles#2]
python setup.py  i get this error:

Traceback (most recent call last):
  File "/home/sino/Downloads/nocthoughts-dotfiles/setup.py", line 133, in <module>
    DotFileSetup.main()
TypeError: DotFileSetup.main() missing 1 required positional argument: 'self'

**Comment by Unhall0w3d** [comment]
Seyhadot,

The script has been entirely re-written in bash and the config setup has been modified. Try again:

sudo rm -r nocthoughts-dotfiles
git clone https://github.com/Unhall0w3d/nocthoughts-dotfiles/.git
cd nocthoughts-dotfiles
sudo chmod +x setup.sh
./setup.sh

The only requirement should be "git" being installed, and Paru, but the script prompts you to install Paru.

**Comment by Unhall0w3d** [comment]
Closing this issue. Please see the readme for the required steps, or my previous post. The script, and repo, were heavily modified since seyhadot's last attempt and the python script is no longer applicable.

If there are any issues please raise it against it anew against the current iteration (bash script).
